# Generated by Django 4.0 on 2022-01-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_userprofile_website_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=30)),
                ('property_type', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('Location', models.CharField(blank=True, max_length=30)),
                ('property_title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('land_area', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('bedroom', models.IntegerField(blank=True)),
                ('bathroom', models.IntegerField(blank=True)),
                ('expiry_date', models.DateField()),
                ('img', models.ImageField(upload_to='pics')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
            ],
        ),
    ]
