# Generated by Django 4.0 on 2022-01-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_img2_listing_img3_alter_listing_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.AddField(
            model_name='listing',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img2',
            field=models.ImageField(blank=True, upload_to='pics', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img3',
            field=models.ImageField(blank=True, upload_to='pics', verbose_name='Image 3'),
        ),
    ]
