# Generated by Django 4.0 on 2022-01-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_remove_listing_description_listing_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathroom',
            field=models.IntegerField(blank=True, verbose_name='BathRooms(leave blank for plat)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedroom',
            field=models.IntegerField(blank=True, verbose_name='BedRooms(leave blank for plat)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Property Type(plat or house)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='purpose',
            field=models.CharField(blank=True, max_length=30, verbose_name='Purpose(rent or sale)'),
        ),
    ]
