# Generated by Django 4.0 on 2022-02-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listing_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='title',
        ),
    ]
