# Generated by Django 4.0 on 2022-02-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_remove_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
    ]
