# Generated by Django 4.0 on 2022-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_listing_img_alter_listing_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
