# Generated by Django 4.0 on 2022-02-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_remove_listing_city_listing_agentcity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='expiry_date',
            new_name='submitOn',
        ),
    ]
