# Generated by Django 4.0 on 2022-02-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_alter_listing_img2_alter_listing_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
