# Generated by Django 4.0 on 2022-03-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_listing_contact_listing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rental_price',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
