# Generated by Django 4.0 on 2022-04-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_alter_listing_agentcity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
