# Generated by Django 4.0 on 2022-01-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='website_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
