# Generated by Django 4.0 on 2022-04-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('agentDirectory', '0017_alter_agentdir_batch_id'),
        ('accounts', '0003_userprofile_address_userprofile_batch_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
