# Generated by Django 4.0 on 2022-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='batch_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='isGold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isPlatinum',
            field=models.BooleanField(default=False),
        ),
    ]
