# Generated by Django 4.0 on 2022-04-30 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0017_alter_agentdir_batch_id'),
        ('accounts', '0006_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='AgentCity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatedRegisteredAgentCity', to='agentDirectory.agentcity'),
        ),
    ]
