# Generated by Django 4.0 on 2022-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=380)),
                ('duration', models.IntegerField(max_length=100)),
                ('prince', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
