# Generated by Django 4.0 on 2022-01-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0002_alter_package_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='userPackage',
        ),
    ]
