# Generated by Django 4.0 on 2022-01-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0003_rename_package_userpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='desc',
            field=models.TextField(),
        ),
    ]
