# Generated by Django 4.0 on 2022-01-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0004_alter_userpackage_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
