# Generated by Django 4.0 on 2022-01-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0005_alter_userpackage_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='userService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('duration', models.IntegerField()),
                ('prince', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
