# Generated by Django 4.0 on 2022-01-25 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0006_userservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservice',
            old_name='prince',
            new_name='charges',
        ),
        migrations.RenameField(
            model_name='userservice',
            old_name='package_name',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='userpackage',
            name='duration',
        ),
        migrations.CreateModel(
            name='package_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminPannel.userpackage')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminPannel.userservice')),
            ],
        ),
    ]
