# Generated by Django 4.0 on 2022-01-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0008_remove_userservice_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='userOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='services_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='Duration(month)')),
                ('offer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminPannel.useroffer')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminPannel.userservice')),
            ],
        ),
    ]
