# Generated by Django 4.0 on 2022-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0009_useroffer_services_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services_offer',
            name='duration',
        ),
        migrations.AddField(
            model_name='useroffer',
            name='duration',
            field=models.IntegerField(default=2, verbose_name='Duration(Days)'),
            preserve_default=False,
        ),
    ]
