# Generated by Django 4.0 on 2022-01-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0011_userpackage_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroffer',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Offer Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpackage',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
