# Generated by Django 4.0 on 2022-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0012_useroffer_name_alter_userpackage_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeAdress', models.CharField(max_length=50, verbose_name='office address')),
                ('officeContact', models.CharField(max_length=120, verbose_name='Office Contact')),
                ('officeMobile', models.CharField(max_length=50, verbose_name='Ofice Mobile')),
                ('officeEmail', models.CharField(max_length=50, verbose_name='Email')),
                ('WorkingHourse', models.CharField(max_length=100, verbose_name='working Hourse and Office Time')),
            ],
        ),
    ]
