# Generated by Django 4.0 on 2022-03-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0014_adminsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='homeSliderImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Home Image(size: width=2000px, hight=1000)'),
        ),
    ]
