# Generated by Django 4.0 on 2022-03-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0017_adminsettings_homesliderimage2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='homeSliderImage1',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='homeSliderImage2',
        ),
    ]
