# Generated by Django 4.0 on 2022-04-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0019_adminsettings_midbanner_adminsettings_sidebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='homePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeSliderImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Home Image 1 (size: width=2000px, hight=1000)')),
                ('headerTextHeading', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='homeSliderImage',
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='midBanner',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='horizentalBanner size(width=750px, height=150px'),
        ),
    ]
