# Generated by Django 4.0 on 2022-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0020_homepage_remove_adminsettings_homesliderimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='headerTextDescription',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='headerTextHeading',
            field=models.CharField(max_length=150, verbose_name='Heading'),
        ),
    ]
