# Generated by Django 4.0 on 2022-04-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0022_remove_homepage_headertextdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='headerTextHeading',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Heading'),
        ),
    ]
