# Generated by Django 4.0 on 2022-02-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentCity',
        ),
    ]
