# Generated by Django 4.0 on 2022-01-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneNo', models.IntegerField(verbose_name='phone Number')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
