# Generated by Django 4.0 on 2022-01-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdir',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
