# Generated by Django 4.0 on 2022-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0002_agentdir_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdir',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Phone Number'),
        ),
    ]
