# Generated by Django 4.0 on 2022-02-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0003_alter_agentdir_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdir',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
