# Generated by Django 4.0 on 2022-02-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0004_agentdir_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdir',
            name='status',
        ),
    ]
