# Generated by Django 4.0 on 2022-02-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0005_remove_agentdir_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='agentdir',
            name='city',
        ),
        migrations.AddField(
            model_name='agentdir',
            name='AgentCity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentDirectory.agentcity'),
        ),
    ]
