# Generated by Django 4.0 on 2022-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0006_agentcity_remove_agentdir_city_agentdir_agentcity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdir',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
