# Generated by Django 4.0 on 2022-02-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0008_agentdir_isfeatured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdir',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentdir',
            name='status',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
