# Generated by Django 4.0 on 2022-03-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0009_alter_agentdir_address_alter_agentdir_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdir',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentdir',
            name='name',
            field=models.CharField(max_length=230),
        ),
    ]
