# Generated by Django 4.0 on 2022-03-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0010_alter_agentdir_address_alter_agentdir_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdir',
            name='email_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agentdir',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
