# Generated by Django 4.0 on 2022-03-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0011_agentdir_email_address_agentdir_facebook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdir',
            name='batch',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
