# Generated by Django 4.0 on 2022-03-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0012_agentdir_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdir',
            name='website_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
