# Generated by Django 4.0 on 2022-03-10 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0013_agentdir_website_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=230)),
            ],
        ),
        migrations.RemoveField(
            model_name='agentdir',
            name='batch',
        ),
        migrations.AddField(
            model_name='agentdir',
            name='batch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentDirectory.batch'),
        ),
    ]
