# Generated by Django 4.0 on 2022-03-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agentDirectory', '0015_alter_agentdir_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdir',
            name='AgentCity_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatedAgentCity', to='agentDirectory.agentcity'),
        ),
    ]
